In [1]:
import pandas as pd

In [ ]:
file_path="D:\\Project DS\\ICRISAT-District Level Data - ICRISAT-District Level Data.csv"
df = pd.read_csv(file_path)

In [5]:
print("Shape of dataset:",df.shape)

Shape of dataset: (16146, 80)

print(df.head())

In [7]:
print(df.dtypes)

Dist Code                                 int64
Year                                      int64
State Code                                int64
State Name                               object
Dist Name                                object
                                         ...
VEGETABLES AREA (1000 ha)               float64
FRUITS AND VEGETABLES AREA (1000 ha)    float64
POTATOES AREA (1000 ha)                 float64
ONION AREA (1000 ha)                    float64
FODDER AREA (1000 ha)                   float64
Length: 80, dtype: object

In [11]:
print(df.isnull().sum())

Dist Code                               0
Year                                    0
State Code                              0
State Name                              0
Dist Name                               0
                                       ..
VEGETABLES AREA (1000 ha)               0
FRUITS AND VEGETABLES AREA (1000 ha)    0
POTATOES AREA (1000 ha)                 0
ONION AREA (1000 ha)                    0
FODDER AREA (1000 ha)                   0
Length: 80, dtype: int64

In [13]:
print("Duplicate rows:",df.duplicated().sum())

Duplicate rows: 0

In [15]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")

In [17]:
print(df.columns)

Index(['dist_code', 'year', 'state_code', 'state_name', 'dist_name',
       'rice_area_(1000_ha)', 'rice_production_(1000_tons)',
       'rice_yield_(kg_per_ha)', 'wheat_area_(1000_ha)',
       'wheat_production_(1000_tons)', 'wheat_yield_(kg_per_ha)',
       'kharif_sorghum_area_(1000_ha)',
       'kharif_sorghum_production_(1000_tons)',
       'kharif_sorghum_yield_(kg_per_ha)', 'rabi_sorghum_area_(1000_ha)',
       'rabi_sorghum_production_(1000_tons)', 'rabi_sorghum_yield_(kg_per_ha)',
       'sorghum_area_(1000_ha)', 'sorghum_production_(1000_tons)',
       'sorghum_yield_(kg_per_ha)', 'pearl_millet_area_(1000_ha)',
       'pearl_millet_production_(1000_tons)', 'pearl_millet_yield_(kg_per_ha)',
       'maize_area_(1000_ha)', 'maize_production_(1000_tons)',
       'maize_yield_(kg_per_ha)', 'finger_millet_area_(1000_ha)',
       'finger_millet_production_(1000_tons)',
       'finger_millet_yield_(kg_per_ha)', 'barley_area_(1000_ha)',
       'barley_production_(1000_tons)', 'barley_yield_(kg_per_ha)',
       'chickpea_area_(1000_ha)', 'chickpea_production_(1000_tons)',
       'chickpea_yield_(kg_per_ha)', 'pigeonpea_area_(1000_ha)',
       'pigeonpea_production_(1000_tons)', 'pigeonpea_yield_(kg_per_ha)',
       'minor_pulses_area_(1000_ha)', 'minor_pulses_production_(1000_tons)',
       'minor_pulses_yield_(kg_per_ha)', 'groundnut_area_(1000_ha)',
       'groundnut_production_(1000_tons)', 'groundnut_yield_(kg_per_ha)',
       'sesamum_area_(1000_ha)', 'sesamum_production_(1000_tons)',
       'sesamum_yield_(kg_per_ha)', 'rapeseed_and_mustard_area_(1000_ha)',
       'rapeseed_and_mustard_production_(1000_tons)',
       'rapeseed_and_mustard_yield_(kg_per_ha)', 'safflower_area_(1000_ha)',
       'safflower_production_(1000_tons)', 'safflower_yield_(kg_per_ha)',
       'castor_area_(1000_ha)', 'castor_production_(1000_tons)',
       'castor_yield_(kg_per_ha)', 'linseed_area_(1000_ha)',
       'linseed_production_(1000_tons)', 'linseed_yield_(kg_per_ha)',
       'sunflower_area_(1000_ha)', 'sunflower_production_(1000_tons)',
       'sunflower_yield_(kg_per_ha)', 'soyabean_area_(1000_ha)',
       'soyabean_production_(1000_tons)', 'soyabean_yield_(kg_per_ha)',
       'oilseeds_area_(1000_ha)', 'oilseeds_production_(1000_tons)',
       'oilseeds_yield_(kg_per_ha)', 'sugarcane_area_(1000_ha)',
       'sugarcane_production_(1000_tons)', 'sugarcane_yield_(kg_per_ha)',
       'cotton_area_(1000_ha)', 'cotton_production_(1000_tons)',
       'cotton_yield_(kg_per_ha)', 'fruits_area_(1000_ha)',
       'vegetables_area_(1000_ha)', 'fruits_and_vegetables_area_(1000_ha)',
       'potatoes_area_(1000_ha)', 'onion_area_(1000_ha)',
       'fodder_area_(1000_ha)'],
      dtype='object')

In [19]:
print(df.columns.tolist())

['dist_code', 'year', 'state_code', 'state_name', 'dist_name', 'rice_area_(1000_ha)', 'rice_production_(1000_tons)', 'rice_yield_(kg_per_ha)', 'wheat_area_(1000_ha)', 'wheat_production_(1000_tons)', 'wheat_yield_(kg_per_ha)', 'kharif_sorghum_area_(1000_ha)', 'kharif_sorghum_production_(1000_tons)', 'kharif_sorghum_yield_(kg_per_ha)', 'rabi_sorghum_area_(1000_ha)', 'rabi_sorghum_production_(1000_tons)', 'rabi_sorghum_yield_(kg_per_ha)', 'sorghum_area_(1000_ha)', 'sorghum_production_(1000_tons)', 'sorghum_yield_(kg_per_ha)', 'pearl_millet_area_(1000_ha)', 'pearl_millet_production_(1000_tons)', 'pearl_millet_yield_(kg_per_ha)', 'maize_area_(1000_ha)', 'maize_production_(1000_tons)', 'maize_yield_(kg_per_ha)', 'finger_millet_area_(1000_ha)', 'finger_millet_production_(1000_tons)', 'finger_millet_yield_(kg_per_ha)', 'barley_area_(1000_ha)', 'barley_production_(1000_tons)', 'barley_yield_(kg_per_ha)', 'chickpea_area_(1000_ha)', 'chickpea_production_(1000_tons)', 'chickpea_yield_(kg_per_ha)', 'pigeonpea_area_(1000_ha)', 'pigeonpea_production_(1000_tons)', 'pigeonpea_yield_(kg_per_ha)', 'minor_pulses_area_(1000_ha)', 'minor_pulses_production_(1000_tons)', 'minor_pulses_yield_(kg_per_ha)', 'groundnut_area_(1000_ha)', 'groundnut_production_(1000_tons)', 'groundnut_yield_(kg_per_ha)', 'sesamum_area_(1000_ha)', 'sesamum_production_(1000_tons)', 'sesamum_yield_(kg_per_ha)', 'rapeseed_and_mustard_area_(1000_ha)', 'rapeseed_and_mustard_production_(1000_tons)', 'rapeseed_and_mustard_yield_(kg_per_ha)', 'safflower_area_(1000_ha)', 'safflower_production_(1000_tons)', 'safflower_yield_(kg_per_ha)', 'castor_area_(1000_ha)', 'castor_production_(1000_tons)', 'castor_yield_(kg_per_ha)', 'linseed_area_(1000_ha)', 'linseed_production_(1000_tons)', 'linseed_yield_(kg_per_ha)', 'sunflower_area_(1000_ha)', 'sunflower_production_(1000_tons)', 'sunflower_yield_(kg_per_ha)', 'soyabean_area_(1000_ha)', 'soyabean_production_(1000_tons)', 'soyabean_yield_(kg_per_ha)', 'oilseeds_area_(1000_ha)', 'oilseeds_production_(1000_tons)', 'oilseeds_yield_(kg_per_ha)', 'sugarcane_area_(1000_ha)', 'sugarcane_production_(1000_tons)', 'sugarcane_yield_(kg_per_ha)', 'cotton_area_(1000_ha)', 'cotton_production_(1000_tons)', 'cotton_yield_(kg_per_ha)', 'fruits_area_(1000_ha)', 'vegetables_area_(1000_ha)', 'fruits_and_vegetables_area_(1000_ha)', 'potatoes_area_(1000_ha)', 'onion_area_(1000_ha)', 'fodder_area_(1000_ha)']

In [21]:
# Step 4A: Convert units (multiply 1000_ha and 1000_tons columns by 1000)
for col in df.columns:
    if "area_(1000_ha)" in col or "production_(1000_tons)" in col:
        df[col] = df[col] * 1000

# Step 4B: Rename columns to base units (ha and tons)
df.rename(columns=lambda x: x.replace("_(1000_ha)", "_(ha)").replace("_(1000_tons)", "_(tons)"), inplace=True)

# Confirm that the renaming worked
print([col for col in df.columns if "1000" in col])  # should return []

[]

In [23]:
print(df.columns.tolist())

['dist_code', 'year', 'state_code', 'state_name', 'dist_name', 'rice_area_(ha)', 'rice_production_(tons)', 'rice_yield_(kg_per_ha)', 'wheat_area_(ha)', 'wheat_production_(tons)', 'wheat_yield_(kg_per_ha)', 'kharif_sorghum_area_(ha)', 'kharif_sorghum_production_(tons)', 'kharif_sorghum_yield_(kg_per_ha)', 'rabi_sorghum_area_(ha)', 'rabi_sorghum_production_(tons)', 'rabi_sorghum_yield_(kg_per_ha)', 'sorghum_area_(ha)', 'sorghum_production_(tons)', 'sorghum_yield_(kg_per_ha)', 'pearl_millet_area_(ha)', 'pearl_millet_production_(tons)', 'pearl_millet_yield_(kg_per_ha)', 'maize_area_(ha)', 'maize_production_(tons)', 'maize_yield_(kg_per_ha)', 'finger_millet_area_(ha)', 'finger_millet_production_(tons)', 'finger_millet_yield_(kg_per_ha)', 'barley_area_(ha)', 'barley_production_(tons)', 'barley_yield_(kg_per_ha)', 'chickpea_area_(ha)', 'chickpea_production_(tons)', 'chickpea_yield_(kg_per_ha)', 'pigeonpea_area_(ha)', 'pigeonpea_production_(tons)', 'pigeonpea_yield_(kg_per_ha)', 'minor_pulses_area_(ha)', 'minor_pulses_production_(tons)', 'minor_pulses_yield_(kg_per_ha)', 'groundnut_area_(ha)', 'groundnut_production_(tons)', 'groundnut_yield_(kg_per_ha)', 'sesamum_area_(ha)', 'sesamum_production_(tons)', 'sesamum_yield_(kg_per_ha)', 'rapeseed_and_mustard_area_(ha)', 'rapeseed_and_mustard_production_(tons)', 'rapeseed_and_mustard_yield_(kg_per_ha)', 'safflower_area_(ha)', 'safflower_production_(tons)', 'safflower_yield_(kg_per_ha)', 'castor_area_(ha)', 'castor_production_(tons)', 'castor_yield_(kg_per_ha)', 'linseed_area_(ha)', 'linseed_production_(tons)', 'linseed_yield_(kg_per_ha)', 'sunflower_area_(ha)', 'sunflower_production_(tons)', 'sunflower_yield_(kg_per_ha)', 'soyabean_area_(ha)', 'soyabean_production_(tons)', 'soyabean_yield_(kg_per_ha)', 'oilseeds_area_(ha)', 'oilseeds_production_(tons)', 'oilseeds_yield_(kg_per_ha)', 'sugarcane_area_(ha)', 'sugarcane_production_(tons)', 'sugarcane_yield_(kg_per_ha)', 'cotton_area_(ha)', 'cotton_production_(tons)', 'cotton_yield_(kg_per_ha)', 'fruits_area_(ha)', 'vegetables_area_(ha)', 'fruits_and_vegetables_area_(ha)', 'potatoes_area_(ha)', 'onion_area_(ha)', 'fodder_area_(ha)']

In [33]:
# Optional: Preview key columns
print(df[['rice_area_(ha)', 'rice_production_(tons)', 'wheat_area_(ha)']].head())

   rice_area_(ha)  rice_production_(tons)  wheat_area_(ha)
0        548000.0                185000.0          44000.0
1        547000.0                409000.0          50000.0
2        556300.0                468000.0          53700.0
3        563400.0                400800.0          49400.0
4        571600.0                473600.0          44200.0

In [25]:
# Select all numeric columns
numeric_cols= df.select_dtypes(include=['float64','int64']).columns

In [27]:
# Check how many negative values are in each numeric column
negatives = (df[numeric_cols] < 0).sum()
print(negatives[negatives > 0])

rice_area_(ha)                      22
rice_production_(tons)              22
rice_yield_(kg_per_ha)              22
wheat_area_(ha)                     35
wheat_production_(tons)             35
                                  ...
vegetables_area_(ha)               289
fruits_and_vegetables_area_(ha)    287
potatoes_area_(ha)                  34
onion_area_(ha)                    317
fodder_area_(ha)                   887
Length: 75, dtype: int64

In [29]:
import numpy as np
# Replace negative values with NaN
df[numeric_cols] = df[numeric_cols].mask(df[numeric_cols] < 0,np.nan)

In [31]:
df.head()

,dist_code,year,state_code,state_name,dist_name,rice_area_(ha),rice_production_(tons),rice_yield_(kg_per_ha),wheat_area_(ha),wheat_production_(tons),...,sugarcane_yield_(kg_per_ha),cotton_area_(ha),cotton_production_(tons),cotton_yield_(kg_per_ha),fruits_area_(ha),vegetables_area_(ha),fruits_and_vegetables_area_(ha),potatoes_area_(ha),onion_area_(ha),fodder_area_(ha)
0,1,1966,14,Chhattisgarh,Durg,548000.0,185000.0,337.59,44000.0,20000.0,...,1777.78,0.0,0.0,0.0,5950.0,6640.0,12590.0,10.0,600.0,470.0
1,1,1967,14,Chhattisgarh,Durg,547000.0,409000.0,747.71,50000.0,26000.0,...,1500.00,0.0,0.0,0.0,5770.0,7240.0,13020.0,10.0,560.0,1230.0
2,1,1968,14,Chhattisgarh,Durg,556300.0,468000.0,841.27,53700.0,30000.0,...,1000.00,0.0,0.0,0.0,5410.0,7400.0,12810.0,100.0,580.0,1020.0
3,1,1969,14,Chhattisgarh,Durg,563400.0,400800.0,711.40,49400.0,26500.0,...,1900.00,0.0,0.0,0.0,5520.0,7160.0,12690.0,10.0,560.0,840.0
4,1,1970,14,Chhattisgarh,Durg,571600.0,473600.0,828.55,44200.0,29000.0,...,2000.00,0.0,0.0,0.0,5450.0,7190.0,12640.0,20.0,520.0,420.0

In [35]:
 #Step 5B: Review extremely high yield values (>10,000 kg/ha)
yield_cols =[col for col in df.columns if 'yield_(kg_per_ha)' in col]

for col in yield_cols:
    high_yield_rows = df[df[col] > 10000][['state_name','dist_name','year',col]]
    if not high_yield_rows.empty:
        print(f"\n⚠️ High values found in '{col}':")
        print(high_yield_rows)

⚠️ High values found in 'maize_yield_(kg_per_ha)':
          state_name   dist_name  year  maize_yield_(kg_per_ha)
2540  Andhra Pradesh      Guntur  2010                 11120.22
2547  Andhra Pradesh      Guntur  2017                 10163.33
2755  Andhra Pradesh  Kadapa YSR  2017                 11368.52
9458         Haryana      Rohtak  2016                 21428.57

⚠️ High values found in 'barley_yield_(kg_per_ha)':
      state_name dist_name  year  barley_yield_(kg_per_ha)
16053  Jharkhand    Ranchi  1973                  10562.50
16055  Jharkhand    Ranchi  1975                  14441.86
16056  Jharkhand    Ranchi  1976                  10933.33
16057  Jharkhand    Ranchi  1977                  13067.80

⚠️ High values found in 'chickpea_yield_(kg_per_ha)':
      state_name    dist_name  year  chickpea_yield_(kg_per_ha)
15367      Bihar  Muzaffarpur  2007                    58363.64
15471      Bihar      Saharsa  2007                    32000.00

⚠️ High values found in 'pigeonpea_yield_(kg_per_ha)':
      state_name dist_name  year  pigeonpea_yield_(kg_per_ha)
15987  Jharkhand   Dhanbad  2009                      12402.6

⚠️ High values found in 'minor_pulses_yield_(kg_per_ha)':
     state_name dist_name  year  minor_pulses_yield_(kg_per_ha)
9199    Haryana   Gurgaon  2017                        13153.85
9250    Haryana      Jind  2016                        11326.32
9355    Haryana    Ambala  2017                        12142.86
9407    Haryana    Karnal  2017                        18888.89
9454    Haryana    Rohtak  2012                        11594.27

⚠️ High values found in 'oilseeds_yield_(kg_per_ha)':
             state_name      dist_name  year  oilseeds_yield_(kg_per_ha)
2391     Andhra Pradesh  East Godavari  2017                    18020.91
2436     Andhra Pradesh  West Godavari  2010                    11937.96
2437     Andhra Pradesh  West Godavari  2011                    11738.79
2438     Andhra Pradesh  West Godavari  2012                    11824.89
2439     Andhra Pradesh  West Godavari  2013                    12706.52
2440     Andhra Pradesh  West Godavari  2014                    12898.52
2442     Andhra Pradesh  West Godavari  2016                    14690.97
2443     Andhra Pradesh  West Godavari  2017                    18147.80
2492     Andhra Pradesh        Krishna  2014                    11366.98
2493     Andhra Pradesh        Krishna  2015                    10460.49
2494     Andhra Pradesh        Krishna  2016                    14122.92
2495     Andhra Pradesh        Krishna  2017                    17570.58
3168          Telangana        Khammam  2014                    10464.09
13004  Himachal Pradesh          Kullu  1974                    25500.00

⚠️ High values found in 'sugarcane_yield_(kg_per_ha)':
           state_name      dist_name  year  sugarcane_yield_(kg_per_ha)
2293   Andhra Pradesh  Visakhapatnam  1971                     11270.41
2353   Andhra Pradesh  East Godavari  1979                     10415.84
2354   Andhra Pradesh  East Godavari  1980                     11102.56
2397   Andhra Pradesh  West Godavari  1971                     10603.09
2399   Andhra Pradesh  West Godavari  1973                     10153.28
...               ...            ...   ...                          ...
15267     West Bengal  West Dinajpur  2011                     11530.61
15268     West Bengal  West Dinajpur  2012                     10437.50
15269     West Bengal  West Dinajpur  2013                     13000.00
15270     West Bengal  West Dinajpur  2014                     10581.40
15893           Bihar           Gaya  2015                     10808.45

[706 rows x 4 columns]

In [37]:
for col in yield_cols:
    # Identitfy rows with yield > 10000
    high_yield_mask = df[col] > 10000

    if high_yield_mask.any():
        print(f"🔧 Fixing high values in: {col}")

🔧 Fixing high values in: maize_yield_(kg_per_ha)
🔧 Fixing high values in: barley_yield_(kg_per_ha)
🔧 Fixing high values in: chickpea_yield_(kg_per_ha)
🔧 Fixing high values in: pigeonpea_yield_(kg_per_ha)
🔧 Fixing high values in: minor_pulses_yield_(kg_per_ha)
🔧 Fixing high values in: oilseeds_yield_(kg_per_ha)
🔧 Fixing high values in: sugarcane_yield_(kg_per_ha)

In [39]:
# Replace each high value with the mean yield for that crop in the same state 
for idx in high_yield_mask.index:
    state = df.at[idx,'state_name']
     # Mean yield in that state, ignoring high outliers and NaNs
    state_mean = df[(df['state_name'] == state) & (df[col] <= 10000)][col].mean()
    df.at[idx, col] = state_mean

In [41]:
#1. Check for Any Remaining Negative Values
print("Negative values remaining:",(df[numeric_cols] < 0).sum().sum())

Negative values remaining: 0

In [42]:
 #2.Check for Any Yield Values Still > 10,000
for col in yield_cols:
    max_val = df[col].max()
    if max_val > 10000:
        print(f" Still high in {col}: {max_val}")

 Still high in maize_yield_(kg_per_ha): 21428.57
 Still high in barley_yield_(kg_per_ha): 14441.86
 Still high in chickpea_yield_(kg_per_ha): 58363.64
 Still high in pigeonpea_yield_(kg_per_ha): 12402.6
 Still high in minor_pulses_yield_(kg_per_ha): 18888.89
 Still high in oilseeds_yield_(kg_per_ha): 25500.0
 Still high in sugarcane_yield_(kg_per_ha): 22062.3

In [54]:
for col in yield_cols:
    high_yield_mask = df[col] > 10000
    if high_yield_mask.any():
        print(f"🔧 Replacing high values in: {col}")
        
        # Loop through each row with a high yield
        for idx in df[high_yield_mask].index:
            state = df.at[idx, 'state_name']
            
            # Calculate mean of valid (≤10,000) values in same state
            valid_state_yield = df[(df['state_name'] == state) & (df[col] <= 10000)][col]
            state_mean = valid_state_yield.mean()

            # Only replace if state_mean is not NaN
            if pd.notnull(state_mean):
                df.at[idx, col] = state_mean
            else:
                # If state mean is not available, replace with global mean below threshold
                global_mean = df[df[col] <= 10000][col].mean()
                df.at[idx, col] = global_mean

🔧 Replacing high values in: maize_yield_(kg_per_ha)
🔧 Replacing high values in: barley_yield_(kg_per_ha)
🔧 Replacing high values in: chickpea_yield_(kg_per_ha)
🔧 Replacing high values in: pigeonpea_yield_(kg_per_ha)
🔧 Replacing high values in: minor_pulses_yield_(kg_per_ha)
🔧 Replacing high values in: oilseeds_yield_(kg_per_ha)
🔧 Replacing high values in: sugarcane_yield_(kg_per_ha)

In [70]:
# Check for Unrealistic Outliers in Yields (>10,000 kg/ha)
yield_cols = [col for col in df.columns if "yield" in col.lower()]
for col in yield_cols:
    max_val = df[col].max()
    if max_val > 10000:
        print(f"⚠️ High value in {col}: {max_val}")

In [56]:
for col in yield_cols:
    max_val = df[col].max()
    print(f"✅ Max in {col}: {max_val}")

✅ Max in rice_yield_(kg_per_ha): 5653.83
✅ Max in wheat_yield_(kg_per_ha): 5541.52
✅ Max in kharif_sorghum_yield_(kg_per_ha): 6531.25
✅ Max in rabi_sorghum_yield_(kg_per_ha): 10000.0
✅ Max in sorghum_yield_(kg_per_ha): 5742.59
✅ Max in pearl_millet_yield_(kg_per_ha): 10000.0
✅ Max in maize_yield_(kg_per_ha): 10000.0
✅ Max in finger_millet_yield_(kg_per_ha): 9286.86
✅ Max in barley_yield_(kg_per_ha): 9878.79
✅ Max in chickpea_yield_(kg_per_ha): 5000.0
✅ Max in pigeonpea_yield_(kg_per_ha): 5608.7
✅ Max in minor_pulses_yield_(kg_per_ha): 9169.67
✅ Max in groundnut_yield_(kg_per_ha): 8500.0
✅ Max in sesamum_yield_(kg_per_ha): 6625.0
✅ Max in rapeseed_and_mustard_yield_(kg_per_ha): 10000.0
✅ Max in safflower_yield_(kg_per_ha): 4166.67
✅ Max in castor_yield_(kg_per_ha): 4600.0
✅ Max in linseed_yield_(kg_per_ha): 7000.0
✅ Max in sunflower_yield_(kg_per_ha): 4282.05
✅ Max in soyabean_yield_(kg_per_ha): 3884.06
✅ Max in oilseeds_yield_(kg_per_ha): 10000.0
✅ Max in sugarcane_yield_(kg_per_ha): 10000.0
✅ Max in cotton_yield_(kg_per_ha): 344.20118142217405

In [43]:
print("🧪 Null values after cleaning:")
print(df[numeric_cols].isnull().sum().sort_values(ascending=False).head(10))

🧪 Null values after cleaning:
oilseeds_yield_(kg_per_ha)        1673
oilseeds_production_(tons)        1673
minor_pulses_yield_(kg_per_ha)    1420
minor_pulses_production_(tons)    1354
fodder_area_(ha)                   887
safflower_production_(tons)        786
safflower_yield_(kg_per_ha)        483
fruits_area_(ha)                   347
onion_area_(ha)                    317
vegetables_area_(ha)               289
dtype: int64

In [50]:
for col in df.columns:
    if df[col].isnull().sum() > 0:
        df[col] = df.groupby('state_name')[col].transform(lambda x: x.fillna(x.mean()))

In [74]:
# Check for Duplicate Rows
print(" Duplicate rows:",df.duplicated().sum())

 Duplicate rows: 0

In [52]:
# Check for Missing (NaN) Values in All Columns
print("🧪 Null values after cleaning:")
print(df[numeric_cols].isnull().sum().sort_values(ascending=False).head(10))

🧪 Null values after cleaning:
dist_code                      0
safflower_production_(tons)    0
linseed_yield_(kg_per_ha)      0
linseed_production_(tons)      0
linseed_area_(ha)              0
castor_yield_(kg_per_ha)       0
castor_production_(tons)       0
castor_area_(ha)               0
safflower_yield_(kg_per_ha)    0
safflower_area_(ha)            0
dtype: int64

In [66]:
# Check for Negative Values in All Numeric Columns
import numpy as np

numeric_cols = df.select_dtypes(include=[np.number]).columns
negatives = (df[numeric_cols] < 0).sum()
print("❌ Columns with negative values:")
print(negatives[negatives > 0])

❌ Columns with negative values:
Series([], dtype: int64)

In [60]:
df[['maize_yield_(kg_per_ha)', 'chickpea_yield_(kg_per_ha)', 'rice_yield_(kg_per_ha)']].describe()

,maize_yield_(kg_per_ha),chickpea_yield_(kg_per_ha),rice_yield_(kg_per_ha)
count,16146.000000,16146.000000,16146.000000
mean,1409.105276,626.775253,1488.497383
std,1173.162475,401.884903,954.684675
min,0.000000,0.000000,0.000000
25%,700.000000,386.557500,802.757500
50%,1163.475000,614.455000,1333.210000
75%,1867.217500,881.747500,2113.517500
max,10000.000000,5000.000000,5653.830000

In [62]:
#5. Check for Uniform Column Names (no extra spaces, special chars)
print("🧪 Column name preview:")
print(df.columns.tolist())

🧪 Column name preview:
['dist_code', 'year', 'state_code', 'state_name', 'dist_name', 'rice_area_(ha)', 'rice_production_(tons)', 'rice_yield_(kg_per_ha)', 'wheat_area_(ha)', 'wheat_production_(tons)', 'wheat_yield_(kg_per_ha)', 'kharif_sorghum_area_(ha)', 'kharif_sorghum_production_(tons)', 'kharif_sorghum_yield_(kg_per_ha)', 'rabi_sorghum_area_(ha)', 'rabi_sorghum_production_(tons)', 'rabi_sorghum_yield_(kg_per_ha)', 'sorghum_area_(ha)', 'sorghum_production_(tons)', 'sorghum_yield_(kg_per_ha)', 'pearl_millet_area_(ha)', 'pearl_millet_production_(tons)', 'pearl_millet_yield_(kg_per_ha)', 'maize_area_(ha)', 'maize_production_(tons)', 'maize_yield_(kg_per_ha)', 'finger_millet_area_(ha)', 'finger_millet_production_(tons)', 'finger_millet_yield_(kg_per_ha)', 'barley_area_(ha)', 'barley_production_(tons)', 'barley_yield_(kg_per_ha)', 'chickpea_area_(ha)', 'chickpea_production_(tons)', 'chickpea_yield_(kg_per_ha)', 'pigeonpea_area_(ha)', 'pigeonpea_production_(tons)', 'pigeonpea_yield_(kg_per_ha)', 'minor_pulses_area_(ha)', 'minor_pulses_production_(tons)', 'minor_pulses_yield_(kg_per_ha)', 'groundnut_area_(ha)', 'groundnut_production_(tons)', 'groundnut_yield_(kg_per_ha)', 'sesamum_area_(ha)', 'sesamum_production_(tons)', 'sesamum_yield_(kg_per_ha)', 'rapeseed_and_mustard_area_(ha)', 'rapeseed_and_mustard_production_(tons)', 'rapeseed_and_mustard_yield_(kg_per_ha)', 'safflower_area_(ha)', 'safflower_production_(tons)', 'safflower_yield_(kg_per_ha)', 'castor_area_(ha)', 'castor_production_(tons)', 'castor_yield_(kg_per_ha)', 'linseed_area_(ha)', 'linseed_production_(tons)', 'linseed_yield_(kg_per_ha)', 'sunflower_area_(ha)', 'sunflower_production_(tons)', 'sunflower_yield_(kg_per_ha)', 'soyabean_area_(ha)', 'soyabean_production_(tons)', 'soyabean_yield_(kg_per_ha)', 'oilseeds_area_(ha)', 'oilseeds_production_(tons)', 'oilseeds_yield_(kg_per_ha)', 'sugarcane_area_(ha)', 'sugarcane_production_(tons)', 'sugarcane_yield_(kg_per_ha)', 'cotton_area_(ha)', 'cotton_production_(tons)', 'cotton_yield_(kg_per_ha)', 'fruits_area_(ha)', 'vegetables_area_(ha)', 'fruits_and_vegetables_area_(ha)', 'potatoes_area_(ha)', 'onion_area_(ha)', 'fodder_area_(ha)']

In [64]:
#6. Check Shape (no empty rows or columns)
print(f"🧮 Dataset shape: {df.shape}")
print("✅ Non-empty columns:", df.notnull().any().sum())

🧮 Dataset shape: (16146, 80)
✅ Non-empty columns: 80

In [78]:
# Final Step: Export cleaned data
df.to_csv("cleaned_icrisat_agriculture_data.csv", index=False)
print("✅ Cleaned dataset saved as 'cleaned_icrisat_agriculture_data.csv'")

✅ Cleaned dataset saved as 'cleaned_icrisat_agriculture_data.csv'